# Generated by Django 5.2.6 on 2025-09-22 16:20

import charidfield.fields
import cuid
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_customuser_public_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="public_id",
            field=charidfield.fields.CharIDField(
                default=cuid.cuid,
                editable=False,
                max_length=25,
                prefix="usr_",
                unique=True,
            ),
        ),
    ]
