name: CI

on:
  push:
    branches: ["dev"]
  pull_request:
    branches: ["dev"]

jobs:
  lint-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-test.txt
          pip install pytest-django pytest black isort ruff

      - name: Run Black
        run: black .

      - name: Run isort
        run: isort .

      - name: Run Ruff (auto-fix)
        if: always()
        run: ruff check . --fix

      - name: Run tests
        run: |
            EXIT_CODE=0
            pytest -v || EXIT_CODE=$?
            if [ $EXIT_CODE -eq 5 ]; then
              echo "No tests were collected. Treating as success."
              exit 0
            else
              exit $EXIT_CODE
            fi
