# Generated by Django 5.2.6 on 2025-09-20 11:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0004_product_categories_alter_category_slug"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="categories",
            new_name="category",
        ),
    ]
